services:
  auauth:
    build: 
      context: ./auauth
    ports:
      - "3000:3000"
    volumes:
      - ./auauth:/app
      - ./node_modules:/app/node_modules
    env_file:
      - ./auauth/.env
    depends_on:
      db:
        condition: service_healthy
        
  prevenda:
    build:
      context: ./stellarator
    ports:
      - 5173:5173
    volumes:
      - ./stellarator:/app
      - ./node_modules:/app/node_modules
    env_file:
      - ./stellarator/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: "auauth, prevenda"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pgdata: